# $env:JEKYLL_ENV="production"; bundle exec jekyll serve -w
# $env:JEKYLL_ENV="production"; bundle exec jekyll build

title: Commie Coder Colony
author: Murad &quot;Gness Erquint&quot; Beybalaev
url: https://erquint.github.io # root address of the site
baseurl: /ccc
description: > # description of the site (multiple lines allowed)
  Under construction. Blog appearance and structure subject to change.

permalink: /:slug.html

favicon: "./logo.png" # relative path to site's favicon

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# https://kramdown.gettalong.org/options.html
kramdown:
  input: GFM
  hard_wrap: true

theme: moonwalk # if you are using GitHub Pages, change it to remote_theme: abhinavs/moonwalk
remote_theme: abhinavs/moonwalk

theme_config:
  appearance: "dark" # can be "light", "dark" or "auto"
  back_home_text: "Home" # customize text for homepage link in post layout
  appearance_toggle: false # if appearance can be switched by user
  date_format: "%F" # strftime date format
  timedate_format: "%F %T" # strftime timedate format
  show_description: true # show blog description
  show_navbar: true # show horizontal navbar
  show_footer: true # show footer links in home page,add in _data/home.yml
  show_copyright: true # show copyright notice in footer
  # following keys are used to create home layout
  show_projects: false # show projects as cards, add in _data/home.yml
  show_blog: true # show blog posts added in _posts
  show_tags: false
  show_old_projects: false # show old projects as cards, add in _data/home.yml
  show_misc_list: false # show generic vertical list for misc details, add _data/home.yml
  # options for "home" page
  home:
    title_projects: Projects
    title_misc_list: Misc
    title_blog: Blog
    title_tags: Tags
    title_old_projects: Old projects

highlighter: rouge

sass:
  style: :compressed

